name: janrose
favicon: null
layout_spectrum: 0.7742986371740699
typography_spectrum: 0.6716463617049158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9925277181901038
  lightness: 0.3779567051678896
  saturation: 0.620446524117142
  rhythmicContrast: 0.5943041562568396
purpose: []
